name: Deploy to GitHub Pages

on:
  push: 
    branches:   
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: Build
      run: |
         npm install -g @angular/cli
         npm install
         ng build --prod
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        BRANCH: master
        FOLDER: dist/hrueger
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: dev
